##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################
from dataclasses import dataclass, field
from typing import Any, Optional
from ._AgentDefinition import AgentDefinition
from ._PropertySchema import PropertySchema
from ._Resource import Resource


@dataclass
class AgentManifest:
    """The following represents a manifest that can be used to create agents dynamically.It includes parameters that can be used to configure the agent&#39;s behavior.These parameters include values that can be used as publisher parameters that canbe used to describe additional variables that have been tested and are known to work.Variables described here are then used to project into a prompt agent that can be executed.Once parameters are provided, these can be referenced in the manifest using the following notation:`{{myParameter}}`This allows for dynamic configuration of the agent based on the provided parameters.(This notation is used elsewhere, but only the `param` scope is supported here)
    Attributes
    ----------
    name : str
        Name of the manifest
    displayName : str
        Human-readable name of the manifest
    description : Optional[str]
        Description of the agent's capabilities and purpose
    metadata : Optional[dict[str, Any]]
        Additional metadata including authors, tags, and other arbitrary properties
    template : AgentDefinition
        The agent that this manifest is based on
    parameters : PropertySchema
        Parameters for configuring the agent's behavior and execution
    resources : list[Resource]
        Resources required by the agent, such as models or tools
    """

    name: str = field(default="")
    displayName: str = field(default="")
    description: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None
    template: AgentDefinition = field(default_factory=AgentDefinition)
    parameters: PropertySchema = field(default_factory=PropertySchema)
    resources: list[Resource] = field(default_factory=list)

    @staticmethod
    def load(data: Any) -> "AgentManifest":
        """Load a AgentManifest instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for AgentManifest: {data}")

        # create new instance
        instance = AgentManifest()
        if data is not None and "name" in data:
            instance.name = data["name"]
        if data is not None and "displayName" in data:
            instance.displayName = data["displayName"]
        if data is not None and "description" in data:
            instance.description = data["description"]
        if data is not None and "metadata" in data:
            instance.metadata = data["metadata"]
        if data is not None and "template" in data:
            instance.template = AgentDefinition.load(data["template"])
        if data is not None and "parameters" in data:
            instance.parameters = PropertySchema.load(data["parameters"])
        if data is not None and "resources" in data:
            instance.resources = AgentManifest.load_resources(data["resources"])
        return instance

    @staticmethod
    def load_resources(data: dict | list) -> list[Resource]:
        if isinstance(data, dict):
            # convert simple named resources to list of Resource
            if len(data.keys()) == 1:
                data = [{"name": k, "kind": v} for k, v in data.items()]
            else:
                data = [{"name": k, **v} for k, v in data.items()]
        return [Resource.load(item) for item in data]
