##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################
from abc import ABC
from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class Connection(ABC):
    """Connection configuration for AI agents.`provider`, `kind`, and `endpoint` are required properties here,but this section can accept additional via options.
    Attributes
    ----------
    kind : str
        The Authentication kind for the AI service (e.g., 'key' for API key, 'oauth' for OAuth tokens)
    authenticationMode : str
        The authority level for the connection, indicating under whose authority the connection is made (e.g., 'user', 'agent', 'system')
    usageDescription : Optional[str]
        The usage description for the connection, providing context on how this connection will be used
    """

    kind: str = field(default="")
    authenticationMode: str = field(default="system")
    usageDescription: Optional[str] = field(default="")

    @staticmethod
    def load(data: Any) -> "Connection":
        """Load a Connection instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for Connection: {data}")

        # load polymorphic Connection instance
        instance = Connection.load_kind(data)
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "authenticationMode" in data:
            instance.authenticationMode = data["authenticationMode"]
        if data is not None and "usageDescription" in data:
            instance.usageDescription = data["usageDescription"]
        return instance

    @staticmethod
    def load_kind(data: dict) -> "Connection":
        # load polymorphic Connection instance
        if data is not None and "kind" in data:
            discriminator_value = data["kind"]
            if discriminator_value == "reference":
                return ReferenceConnection.load(data)
            elif discriminator_value == "remote":
                return RemoteConnection.load(data)
            elif discriminator_value == "key":
                return ApiKeyConnection.load(data)
            elif discriminator_value == "anonymous":
                return AnonymousConnection.load(data)
            else:
                raise ValueError(
                    f"Unknown Connection discriminator value: {discriminator_value}"
                )
        else:
            raise ValueError("Missing Connection discriminator property: 'kind'")


@dataclass
class ReferenceConnection(Connection):
    """Connection configuration for AI services using named connections.
    Attributes
    ----------
    kind : str
        The Authentication kind for the AI service (e.g., 'key' for API key, 'oauth' for OAuth tokens)
    name : str
        The name of the connection
    target : Optional[str]
        The target resource or service that this connection refers to
    """

    kind: str = field(default="reference")
    name: str = field(default="")
    target: Optional[str] = field(default="")

    @staticmethod
    def load(data: Any) -> "ReferenceConnection":
        """Load a ReferenceConnection instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ReferenceConnection: {data}")

        # create new instance
        instance = ReferenceConnection()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "name" in data:
            instance.name = data["name"]
        if data is not None and "target" in data:
            instance.target = data["target"]
        return instance


@dataclass
class RemoteConnection(Connection):
    """Connection configuration for AI services using named connections.
    Attributes
    ----------
    kind : str
        The Authentication kind for the AI service (e.g., 'key' for API key, 'oauth' for OAuth tokens)
    name : str
        The name of the connection
    endpoint : str
        The endpoint URL for the AI service
    """

    kind: str = field(default="remote")
    name: str = field(default="")
    endpoint: str = field(default="")

    @staticmethod
    def load(data: Any) -> "RemoteConnection":
        """Load a RemoteConnection instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for RemoteConnection: {data}")

        # create new instance
        instance = RemoteConnection()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "name" in data:
            instance.name = data["name"]
        if data is not None and "endpoint" in data:
            instance.endpoint = data["endpoint"]
        return instance


@dataclass
class ApiKeyConnection(Connection):
    """Connection configuration for AI services using API keys.
    Attributes
    ----------
    kind : str
        The Authentication kind for the AI service (e.g., 'key' for API key, 'oauth' for OAuth tokens)
    endpoint : str
        The endpoint URL for the AI service
    apiKey : str
        The API key for authenticating with the AI service
    """

    kind: str = field(default="key")
    endpoint: str = field(default="")
    apiKey: str = field(default="")

    @staticmethod
    def load(data: Any) -> "ApiKeyConnection":
        """Load a ApiKeyConnection instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ApiKeyConnection: {data}")

        # create new instance
        instance = ApiKeyConnection()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "endpoint" in data:
            instance.endpoint = data["endpoint"]
        if data is not None and "apiKey" in data:
            instance.apiKey = data["apiKey"]
        return instance


@dataclass
class AnonymousConnection(Connection):
    """
    Attributes
    ----------
    kind : str
        The Authentication kind for the AI service (e.g., 'key' for API key, 'oauth' for OAuth tokens)
    endpoint : str
        The endpoint for authenticating with the AI service
    """

    kind: str = field(default="anonymous")
    endpoint: str = field(default="")

    @staticmethod
    def load(data: Any) -> "AnonymousConnection":
        """Load a AnonymousConnection instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for AnonymousConnection: {data}")

        # create new instance
        instance = AnonymousConnection()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "endpoint" in data:
            instance.endpoint = data["endpoint"]
        return instance
