##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################
from abc import ABC
from dataclasses import dataclass, field
from typing import Any


@dataclass
class McpServerApprovalMode(ABC):
    """The approval mode for MCP server tools.
    Attributes
    ----------
    kind : str
        The kind identifier for string approval modes
    """

    kind: str = field(default="")

    @staticmethod
    def load(data: Any) -> "McpServerApprovalMode":
        """Load a McpServerApprovalMode instance."""
        # handle alternate representations
        if isinstance(data, str):
            data = {"kind": data}

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for McpServerApprovalMode: {data}")

        # load polymorphic McpServerApprovalMode instance
        instance = McpServerApprovalMode.load_kind(data)
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        return instance

    @staticmethod
    def load_kind(data: dict) -> "McpServerApprovalMode":
        # load polymorphic McpServerApprovalMode instance
        if data is not None and "kind" in data:
            discriminator_value = data["kind"]
            if discriminator_value == "always":
                return McpServerToolAlwaysRequireApprovalMode.load(data)
            elif discriminator_value == "never":
                return McpServerToolNeverRequireApprovalMode.load(data)
            elif discriminator_value == "specify":
                return McpServerToolSpecifyApprovalMode.load(data)
            else:
                raise ValueError(
                    f"Unknown McpServerApprovalMode discriminator value: {discriminator_value}"
                )
        else:
            raise ValueError(
                "Missing McpServerApprovalMode discriminator property: 'kind'"
            )


@dataclass
class McpServerToolAlwaysRequireApprovalMode(McpServerApprovalMode):
    """
    Attributes
    ----------
    kind : str
        The kind identifier for always approval mode
    """

    kind: str = field(default="always")

    @staticmethod
    def load(data: Any) -> "McpServerToolAlwaysRequireApprovalMode":
        """Load a McpServerToolAlwaysRequireApprovalMode instance."""

        if not isinstance(data, dict):
            raise ValueError(
                f"Invalid data for McpServerToolAlwaysRequireApprovalMode: {data}"
            )

        # create new instance
        instance = McpServerToolAlwaysRequireApprovalMode()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        return instance


@dataclass
class McpServerToolNeverRequireApprovalMode(McpServerApprovalMode):
    """
    Attributes
    ----------
    kind : str
        The kind identifier for never approval mode
    """

    kind: str = field(default="never")

    @staticmethod
    def load(data: Any) -> "McpServerToolNeverRequireApprovalMode":
        """Load a McpServerToolNeverRequireApprovalMode instance."""

        if not isinstance(data, dict):
            raise ValueError(
                f"Invalid data for McpServerToolNeverRequireApprovalMode: {data}"
            )

        # create new instance
        instance = McpServerToolNeverRequireApprovalMode()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        return instance


@dataclass
class McpServerToolSpecifyApprovalMode(McpServerApprovalMode):
    """
    Attributes
    ----------
    kind : str
        The kind identifier for specify approval mode
    alwaysRequireApprovalTools : list[str]
        List of tools that always require approval
    neverRequireApprovalTools : list[str]
        List of tools that never require approval
    """

    kind: str = field(default="specify")
    alwaysRequireApprovalTools: list[str] = field(default_factory=list)
    neverRequireApprovalTools: list[str] = field(default_factory=list)

    @staticmethod
    def load(data: Any) -> "McpServerToolSpecifyApprovalMode":
        """Load a McpServerToolSpecifyApprovalMode instance."""

        if not isinstance(data, dict):
            raise ValueError(
                f"Invalid data for McpServerToolSpecifyApprovalMode: {data}"
            )

        # create new instance
        instance = McpServerToolSpecifyApprovalMode()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "alwaysRequireApprovalTools" in data:
            instance.alwaysRequireApprovalTools = data["alwaysRequireApprovalTools"]
        if data is not None and "neverRequireApprovalTools" in data:
            instance.neverRequireApprovalTools = data["neverRequireApprovalTools"]
        return instance
