##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################
from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class ModelOptions:
    """Options for configuring the behavior of the AI model.`kind` is a required property here, but this section can accept additional via options.
    Attributes
    ----------
    frequencyPenalty : Optional[float]
        The frequency penalty to apply to the model's output
    maxOutputTokens : Optional[int]
        The maximum number of tokens to generate in the output
    presencePenalty : Optional[float]
        The presence penalty to apply to the model's output
    seed : Optional[int]
        A random seed for deterministic output
    temperature : Optional[float]
        The temperature to use for sampling
    topK : Optional[int]
        The top-K sampling value
    topP : Optional[float]
        The top-P sampling value
    stopSequences : Optional[list[str]]
        Stop sequences to end generation
    allowMultipleToolCalls : Optional[bool]
        Whether to allow multiple tool calls in a single response
    additionalProperties : Optional[dict[str, Any]]
        Additional custom properties for model options
    """

    frequencyPenalty: Optional[float] = None
    maxOutputTokens: Optional[int] = None
    presencePenalty: Optional[float] = None
    seed: Optional[int] = None
    temperature: Optional[float] = None
    topK: Optional[int] = None
    topP: Optional[float] = None
    stopSequences: Optional[list[str]] = field(default_factory=list)
    allowMultipleToolCalls: Optional[bool] = None
    additionalProperties: Optional[dict[str, Any]] = None

    @staticmethod
    def load(data: Any) -> "ModelOptions":
        """Load a ModelOptions instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ModelOptions: {data}")

        # create new instance
        instance = ModelOptions()
        if data is not None and "frequencyPenalty" in data:
            instance.frequencyPenalty = data["frequencyPenalty"]
        if data is not None and "maxOutputTokens" in data:
            instance.maxOutputTokens = data["maxOutputTokens"]
        if data is not None and "presencePenalty" in data:
            instance.presencePenalty = data["presencePenalty"]
        if data is not None and "seed" in data:
            instance.seed = data["seed"]
        if data is not None and "temperature" in data:
            instance.temperature = data["temperature"]
        if data is not None and "topK" in data:
            instance.topK = data["topK"]
        if data is not None and "topP" in data:
            instance.topP = data["topP"]
        if data is not None and "stopSequences" in data:
            instance.stopSequences = data["stopSequences"]
        if data is not None and "allowMultipleToolCalls" in data:
            instance.allowMultipleToolCalls = data["allowMultipleToolCalls"]
        if data is not None and "additionalProperties" in data:
            instance.additionalProperties = data["additionalProperties"]
        return instance
