##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ProtocolVersionRecord:
    """
    Attributes
    ----------
    protocol : str
        The protocol type.
    version : str
        The version string for the protocol, e.g. 'v0.1.1'.
    """

    protocol: str = field(default="")
    version: str = field(default="")

    @staticmethod
    def load(data: Any) -> "ProtocolVersionRecord":
        """Load a ProtocolVersionRecord instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ProtocolVersionRecord: {data}")

        # create new instance
        instance = ProtocolVersionRecord()
        if data is not None and "protocol" in data:
            instance.protocol = data["protocol"]
        if data is not None and "version" in data:
            instance.version = data["version"]
        return instance
