##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################
from dataclasses import dataclass, field
from typing import Any, Optional
from ._Property import Property


@dataclass
class PropertySchema:
    """Definition for the property schema of a model.This includes the properties and example records.
    Attributes
    ----------
    examples : Optional[list[dict[str, Any]]]
        Example records for the input schema
    strict : Optional[bool]
        Whether the input schema is strict - if true, only the defined properties are allowed
    properties : list[Property]
        The input properties for the schema
    """

    examples: Optional[list[dict[str, Any]]] = field(default_factory=list)
    strict: Optional[bool] = None
    properties: list[Property] = field(default_factory=list)

    @staticmethod
    def load(data: Any) -> "PropertySchema":
        """Load a PropertySchema instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for PropertySchema: {data}")

        # create new instance
        instance = PropertySchema()
        if data is not None and "examples" in data:
            instance.examples = data["examples"]
        if data is not None and "strict" in data:
            instance.strict = data["strict"]
        if data is not None and "properties" in data:
            instance.properties = PropertySchema.load_properties(data["properties"])
        return instance

    @staticmethod
    def load_properties(data: dict | list) -> list[Property]:
        if isinstance(data, dict):
            # convert simple named properties to list of Property
            if len(data.keys()) == 1:
                data = [{"name": k, "kind": v} for k, v in data.items()]
            else:
                data = [{"name": k, **v} for k, v in data.items()]
        return [Property.load(item) for item in data]
