##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################
from abc import ABC
from dataclasses import dataclass, field
from typing import Any


@dataclass
class Resource(ABC):
    """Represents a resource required by the agentResources can include databases, APIs, or other external systemsthat the agent needs to interact with to perform its tasks
    Attributes
    ----------
    name : str
        Name of the resource
    kind : str
        The kind of resource (e.g., model, tool)
    """

    name: str = field(default="")
    kind: str = field(default="")

    @staticmethod
    def load(data: Any) -> "Resource":
        """Load a Resource instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for Resource: {data}")

        # load polymorphic Resource instance
        instance = Resource.load_kind(data)
        if data is not None and "name" in data:
            instance.name = data["name"]
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        return instance

    @staticmethod
    def load_kind(data: dict) -> "Resource":
        # load polymorphic Resource instance
        if data is not None and "kind" in data:
            discriminator_value = str(data["kind"]).lower()
            if discriminator_value == "model":
                return ModelResource.load(data)
            elif discriminator_value == "tool":
                return ToolResource.load(data)
            else:
                raise ValueError(
                    f"Unknown Resource discriminator value: {discriminator_value}"
                )
        else:
            raise ValueError("Missing Resource discriminator property: 'kind'")


@dataclass
class ModelResource(Resource):
    """Represents a model resource required by the agent
    Attributes
    ----------
    kind : str
        The kind identifier for model resources
    id : str
        The unique identifier of the model resource
    """

    kind: str = field(default="model")
    id: str = field(default="")

    @staticmethod
    def load(data: Any) -> "ModelResource":
        """Load a ModelResource instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ModelResource: {data}")

        # create new instance
        instance = ModelResource()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "id" in data:
            instance.id = data["id"]
        return instance


@dataclass
class ToolResource(Resource):
    """Represents a tool resource required by the agent
    Attributes
    ----------
    kind : str
        The kind identifier for tool resources
    id : str
        The unique identifier of the tool resource
    options : dict[str, Any]
        Configuration options for the tool resource
    """

    kind: str = field(default="tool")
    id: str = field(default="")
    options: dict[str, Any] = field(default_factory=dict)

    @staticmethod
    def load(data: Any) -> "ToolResource":
        """Load a ToolResource instance."""

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ToolResource: {data}")

        # create new instance
        instance = ToolResource()
        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "id" in data:
            instance.id = data["id"]
        if data is not None and "options" in data:
            instance.options = data["options"]
        return instance
